language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - sindre.kroknes@gmail.com
    - magnussh@stud.ntnu.no
    - bjornhaf@stud.ntnu.no

    on_success: never
    on_failure: always
